### ISSUE TITLE
happy to help

### ISSUE THREAD

**Issue by timelyportfolio** [mdsumner/gibble#2]
I somehow missed this until now.  Please let me know how I can help.

**Comment by mdsumner** [comment]
Oh hey, I consider this a kind of necessary side-excursion that I needed to figure out some things :)   
 I feel the need to explain a bit, so read on if you like!  I take it you mean help out with the topological edit?   I think 'gibble' needs to exist, but I'm not sure this is the right form, it's really just a necessary tool in  a bigger context. 

We've settled pretty well on the model provided by  https://github.com/hypertidy/silicate and that currently depends on gibble, but I'm kind of considering building all the logic into silicate itself.  The key was realizing that `sc_coord` is the raw set of all coordinates, and the gibble is the run-length index of the paths in that set. This is a nice intermediate stage, in one direction you go to more topological forms, with all labelled relations as in silicate, in the other direction you reconstruct to sf and related forms.  It's a kind of halfway house, but still set-based and in generic data frame form. We've settled on the *models* and *verbs* structure, laid out in the silicate readme, and that's fairly solid now I think. 

When I did the mapedit/topology example I had only just struck on that as a method for rebuilding sf objects, and that is all now [here](https://github.com/hypertidy/silicate/blob/master/R/spatial-builder.R#L9), but still to be formalized. @mpadge has an independent implementation and we will be merging our learnings in the coming months. 

The topology edit works fine, I left a record here - there's just no live-update when you move a vertex, so it's not so compelling. https://gist.github.com/mdsumner/4e9ebb4ed9fa03682e58128afa66a16c  If you were keen to explore how to make it live, that would be great - I'll be keen to flesh it out and explore again -  but I think it's inevitable that we treat sf as a kind of end-format, not a working-structure in this context.
