### ISSUE TITLE
pkgdown site shows MERGE issue

### ISSUE THREAD

**Issue by espinielli** [mdsumner/gibble#9]
Just to ping about pkgdown site showing MERGE issue:

![Capture](https://user-images.githubusercontent.com/891692/82215981-818d3000-9918-11ea-8fa9-a737e77b953f.PNG)

**Comment by mdsumner** [comment]
ew, thank you!  should be fixed now ;)

**Comment by espinielli** [comment]
it is indeed. Thanks.
